import '@/styles/main.scss'
import type { Metadata } from 'next'
import { Locale, i18n } from '@/i18n.config'
import Header from './components/header/Header'

import { Inter } from 'next/font/google'
const inter = Inter({
  weight: ['400', '500', '700'],
  subsets: ['latin']
 })

export const metadata: Metadata = {
  title: 'CRM',
  description: 'Generated by create next app'
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
}) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <Header lang={params.lang} />
        <main>{children}</main>
      </body>
    </html>
  )
}
